### ISSUE TITLE
Add feemarket to eve

### ISSUE THREAD

**Issue by hoank101** [eve-network/eve#245]
Please add it to eve
https://github.com/skip-mev/feemarket

## Todo
- [ ] Integrate to eve, add unit test(#250)
- [ ] Add integration test
- [ ] Add upgrade handler
- [ ] Add upgrade test

**Comment by faddat** [comment]
The PR looks good to me -- any thoughts here?

**Comment by tropicaldog** [comment]
Need add more tests to ensure the module work properly sir @faddat
